php 8.1 - fix deprecated message
TypeError: count(): Argument #1 () must be of type Countable|array, null given

PHP Deprecated:  DOMDocument::__construct(): Passing null to parameter #2 () of type string is deprecated